### ISSUE TITLE
2.9" Waveshare e-Paper black/white version

### ISSUE THREAD

**Issue by DaveBrindley** [rdagger/MicroPython-2.9-inch-ePaper-Library#1]
Hi - Would you be willing to modify your library so that it will work with the Black/White version of this screen?
This is the version I have - https://www.waveshare.com/pico-epaper-2.9.htm and the datasheet is here:
https://www.waveshare.com/w/upload/7/79/2.9inch-e-paper-v2-specification.pdf

**Comment by rdagger** [comment]
Sorry, I don’t have that version of the display and a cursory look at the datasheet indicates several dissimilarities.
