### ISSUE TITLE
Clean() takes a lot of time

### ISSUE THREAD

**Issue by guidoknoop** [rdagger/MicroPython-2.9-inch-ePaper-Library#2]
Hi,

First of all thanks for this repo! I really needed this. I noticed that the Clean() function takes approx. 30 secondes. Is it possible to speed up this function? Or can I omit the function?

Kind regards,
Guido

**Comment by rdagger** [comment]
Are you referring to the cleanup() method or the clear() method?

**Comment by guidoknoop** [comment]
Sorry! I mean clear().
________________________________
Van: rdagger ***@***.***>
Verzonden: Monday, October 24, 2022 6:52:42 PM
Aan: rdagger/MicroPython-2.9-inch-ePaper-Library ***@***.***>
CC: Guido Knoop ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rdagger/MicroPython-2.9-inch-ePaper-Library] Clean() takes a lot of time (Issue #2)


Are you referring to the cleanup() method or the clear() method?

**Comment by rdagger** [comment]
You only have to run clear() if you want the screen to be blank.  If you want to clear existing graphics before generating new graphics, then you can use clear_buffers() which should take under a second and will give you a blank slate to start drawing on but won't actually update the display until the present() method is called.

I did fix some redundant code in the clear() method which should speed up the clear() method.  I also increased the baud rate in the demos from 14.5 to 34.5 MHz.  This may help performance in some cases.  I was able to run my ESP32 SPI bus up to 60 MHz before I encountered errors, but bus speed can be affected by many factors such as wire length, your board and proximity to other devices.

I never ended up using the epaper display in a project so none of this code has been thoroughly tested or optimized.
